### PR TITLE
fix: update branch name to main

### PR DESCRIPTION
**Pull request by qhuang-f5**
update the ruby.yml file

### CODE REVIEW

**Comment by f5-davey** [comment]
Looks like there was a breaking change we need to adjust to...

```
Error: Unable to process command '::set-env name=PATH::/home/runner/.rubies/ruby-2.6.6/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by qhuang-f5** [comment]
> Looks like there was a breaking change we need to adjust to...
> 
> ```
> Error: Unable to process command '::set-env name=PATH::/home/runner/.rubies/ruby-2.6.6/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' successfully.
> Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> ```

Yes. Looks like we cannot just change the branch name... since the set-env is deprecated by GitHub...

**Comment by f5-davey** [comment]
We should update the setup-ruby image instead of using ACTIONS_ALLOW_UNSECURE_COMMANDS.

Looks like it was fixed at v1.46.1.  Confirmed action passed at ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0.  We could also go with @v1.

**Comment by qhuang-f5** [comment]
> We should update the setup-ruby image instead of using ACTIONS_ALLOW_UNSECURE_COMMANDS.
> 
> Looks like it was fixed at v1.46.1. Confirmed action passed at [ruby/setup-ruby@ec106b4](https://github.com/ruby/setup-ruby/commit/ec106b438a1ff6ff109590de34ddc62c540232e0). We could also go with @v1.

Changed it to @v1 and remove the ACTIONS_ALLOW_UNSECURE_COMMANDS. Thanks Matt!

**Pull request merged**
